---
apiVersion: v1
kind: ConfigMap
metadata:
  name: flux-helm-tls-ca-config
  namespace: flux
data:
  ca.crt: |
    -----BEGIN CERTIFICATE-----
    MIIE6jCCAtKgAwIBAgIUO+c0pGT/jX8GwD0pJzPrBIYSf/YwDQYJKoZIhvcNAQEN
    BQAwDTELMAkGA1UEAxMCQ0EwHhcNMTkwODIyMTI0MDAwWhcNMjQwODIwMTI0MDAw
    WjANMQswCQYDVQQDEwJDQTCCAiIwDQYJKoZIhvcNAQEBBQADggIPADCCAgoCggIB
    AOrTdYxAia9gxrGertkEaTeQow/RFT9seUkG+C9lOW4FoPM+5iu5oEU5w81ud3If
    TuETUY+aGRdHcAQTk8fIMvpGWBLtcHFHuX6wjPHC2cvDIbDvLJhWPqVvupxZZ/bH
    0wnStFBptRVcwneCFeqOa4QcsX54zt2+s6WRzeXocEJb3Z8pRsK+QApVuj280pcF
    JML+FR6cj0A9KvTu4GKJ7crhpjE1hBu2iRajR6d7LUs4jL4+q2FrIkfLrE9j0jiD
    QiM7Rj1V7XJFisscEa3g58CWq00MikVm2P4JC8XMtlB+SLfut6zOPBZ+E1lPZHzC
    jQ+EyAe9LnKE3NOdGtTtQ3Z3ALt+28On0V8NSuVi46I6B5b9hlhCnYA17S/sYFMO
    j11hpDfYY1qAZQyz7/mE8/JNIS2S3vlBT61EegcHxiV3YSJiHJl0MSg4PEJeijiv
    mmLjl+O+F4xKbI4lKiqQpwZGGnoTLm18IEX9MtXZ7CEUqswZ1gaalN6ZJkol1v/m
    jgCIejGEinb6fRDWJTcT6yUHtCKftG9Zrc/HKAGBrvW7vIg8X7LyEGEV+qyx35nj
    JM7J3leBOgVTRZMIWvTht0RzINJ2+5ByoBonccPIdTmBrCp+EZ5UJSnkbWkaPCeT
    YhcE2S6/md2AOZa6ozE5kCyAVFuwuEuRtqaeK95BxyarAgMBAAGjQjBAMA4GA1Ud
    DwEB/wQEAwIBBjAPBgNVHRMBAf8EBTADAQH/MB0GA1UdDgQWBBTHxs+87VGwgEja
    4fuuhy2XqURCUDANBgkqhkiG9w0BAQ0FAAOCAgEAPStikVYrUFVhyeFqQJrLXu27
    +KDpj4YgyaTCXyO9Ca1YPFVDPmoCRo7kQr0sPBtxc+s8qDLCiazg89b024T+z0mr
    XhukqpFerHksaXfhRxbRKLevluez5FGwROAUzqtn50ddv/IYPQwEWZB45i37LIRo
    l2pQ6LU14aVh5G5adzqyYlP54f8Hb8xQwFhBD6x4G/KzGkOayBzAFjxV76V3ud9o
    PXMZLYaEbexX9MDRdBZy1LMmHRhAk1r+WpzJIQxsiR0OfON8vP4lfsMaBr5iY2uW
    7YkbCPZ7xUq0bJND/Z9hM+zixZxGyAcNGjRzkPVkbjvH3If+rnU4qzQa4h8vyYGJ
    EXedpLaAZG1pffR473xFKLJVE8L1W0Bp1hCHY15mKXUQXlfo0ljvO+0NckFDNILn
    tHvknlZc8H6RW0IoreZFuPsYLLNP7Kcq0K4jadqg8toTvZ/VeKGSmWpqNUXFeVqJ
    DS0HsNC5pRqvPx4+CEL5ShAfNiAicktUcgUs10CPjBrp6L/hTwdruzAwss5s9aHO
    Bg1MbQdgTa8K21TzLWdzDuPePQqTxYb4bSTt/c8S/YYeMV8EIiwSOJS0TbDC9yzw
    NyJ/qnCw7Ns3kUFVnth57ngZmrNZUB9Q4VSrTrfRq2DszNMAXxXwezNwjyi2GaNH
    OHbrFSEgeTD+tI+O0GE=
    -----END CERTIFICATE-----
    
